# name: Test Debian Package

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container:
#       image: debian:latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Setup Debian software sources
#       run: |
#         echo "deb http://deb.debian.org/debian/ bullseye main" | tee /etc/apt/sources.list
#         echo "deb http://deb.debian.org/debian/ bullseye-updates main" | tee -a /etc/apt/sources.list
#         echo "deb http://security.debian.org/ bullseye-security main" | tee -a /etc/apt/sources.list
#         echo "deb http://deb.debian.org/debian unstable main" | tee -a /etc/apt/sources.list

#     - name: Set up Debian packaging environment
#       run: |
#         apt-get update -q
#         apt-get install -y devscripts debhelper build-essential lintian fakeroot meson libwlroots-dev libwayland-dev doxygen graphviz 
#         apt-get install -y libxslt1-dev xmlto wayland-protocols libsystemd-dev libdrm-dev libxcb1-dev libxcb-icccm4-dev libxml2-dev libcairo2-dev libpango1.0-dev libxpm-dev libjpeg-dev librsvg2-dev

#     - name: Build the package
#       run: |
#         dpkg-buildpackage -us -uc -b

#     - name: Run lintian
#       run: |
#         lintian ../*.deb | tee lintian.log

#     - name: Upload Debian package
#       uses: actions/upload-artifact@v2
#       with:
#         name: wsm
#         path: ../*.deb

#     - name: Upload lintian report
#       uses: actions/upload-artifact@v2
#       with:
#         name: lintian-report
#         path: lintian.log